{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"KeyError: 'url'\n","children":[{"name":"Fail Test","uid":"c38f3ccaf84da03","parentUid":"3a3a14b5cc9866fa188cf762836183ed","status":"broken","time":{"start":1727100416005,"stop":1727100416008,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":9,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3a3a14b5cc9866fa188cf762836183ed"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=37141): Max retries exceeded with url: /session/fc8eb2ec948741490d5d64b192f74f73/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f751ac045b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n","children":[{"name":"Fail This Test For Report -- @1.1 ","uid":"16d530e718fae3d8","parentUid":"30117c0fced15c329ae44a22ba5ab987","status":"broken","time":{"start":1727121505120,"stop":1727121505128,"duration":8},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":["WrongPassword","John Doe"],"tags":["severity.minor","ui","positive"]}],"uid":"30117c0fced15c329ae44a22ba5ab987"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}