{"name": "Valid login to katalon-demo-cura application -- @1.1 ", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=48239): Max retries exceeded with url: /session/182ed2b93db7bbf3748c69ce5ef84bff/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2823456af0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 50, in after_step\n    context.driver.save_screenshot(screenshot_path)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 829, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 805, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 306, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 326, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "steps": [{"name": "Given I am on the login page \"https://katalon-demo-cura.herokuapp.com/profile.php\"", "status": "passed", "steps": [{"name": "User navigates to login page 'https://katalon-demo-cura.herokuapp.com/profile.php'", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x7f2823d9e370>"}, {"name": "url", "value": "'https://katalon-demo-cura.herokuapp.com/profile.php'"}], "start": 1727098642140, "stop": 1727098642466}], "attachments": [{"name": "I am on the login page _https___katalon-demo-cura.herokuapp.com_profile.php__passed.png", "source": "755a3158-f1f8-4414-bf99-8b98f29913aa-attachment.png", "type": "image/png"}], "start": 1727098642140, "stop": 1727098642762}, {"name": "When I enter a valid username \"John Doe\" and password \"ThisIsNotAPassword\"", "status": "passed", "steps": [{"name": "User can enter username - \"'John Doe'\" and password - \"'ThisIsNotAPassword'\"", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x7f2823d9e370>"}, {"name": "username", "value": "'John Doe'"}, {"name": "password", "value": "'ThisIsNotAPassword'"}], "start": 1727098642762, "stop": 1727098642875}], "attachments": [{"name": "I enter a valid username _John Doe_ and password _ThisIsNotAPassword__passed.png", "source": "317476a0-f9ab-4289-a0ec-19ec45d14d4e-attachment.png", "type": "image/png"}], "start": 1727098642762, "stop": 1727098643122}, {"name": "And I click the login button", "status": "passed", "steps": [{"name": "User can can click on login button", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x7f2823d9e370>"}], "start": 1727098643123, "stop": 1727098643241}], "attachments": [{"name": "I click the login button_passed.png", "source": "426eb821-3df6-4ce1-954b-0e65c96478bb-attachment.png", "type": "image/png"}], "start": 1727098643122, "stop": 1727098643414}, {"name": "Then I should be redirected to the dashboard page", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=48239): Max retries exceeded with url: /session/182ed2b93db7bbf3748c69ce5ef84bff/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2823456af0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 50, in after_step\n    context.driver.save_screenshot(screenshot_path)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 829, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 805, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 306, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 326, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "steps": [{"name": "User login successfully and can see home page", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x7f2823d9e370>"}], "start": 1727098643414, "stop": 1727098643482}], "start": 1727098643414, "stop": 1727098643486}], "parameters": [{"name": "username", "value": "John Doe"}, {"name": "password", "value": "ThisIsNotAPassword"}], "start": 1727098642140, "stop": 1727098643487, "uuid": "30781e5f-d2b1-412c-8013-d30e301d79cb", "historyId": "e83a6604cc6352825a2b4b2f8b5425cb", "fullName": "User Login to katalon-demo-cura application: Valid login to katalon-demo-cura application", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login to katalon-demo-cura application"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}