{"name": "Fail Test", "status": "broken", "statusDetails": {"message": "KeyError: 'url'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n"}, "steps": [{"name": "Given I am failure", "status": "broken", "statusDetails": {"message": "KeyError: 'url'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n"}, "attachments": [{"name": "I_am_failure_failed.png", "source": "5f4cbc00-1f20-4462-abbf-7b36d780e961-attachment.png", "type": "image/png"}], "start": 1727098365661, "stop": 1727098365901}], "start": 1727098365661, "stop": 1727098365901, "uuid": "e63bca84-14f8-47c5-b2fa-01c65827cc2c", "historyId": "d3d39de6fc3cd407f5d66e2d343702f9", "fullName": "User Login to katalon-demo-cura application: Fail Test", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login to katalon-demo-cura application"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}