{"name": "Fail Test", "status": "broken", "statusDetails": {"message": "KeyError: 'url'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n"}, "steps": [{"name": "Given I am failure", "status": "broken", "statusDetails": {"message": "KeyError: 'url'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n"}, "attachments": [{"name": "I_am_failure_failed.png", "source": "a7cc46ec-a1ba-4293-b5ad-fd147bf46c28-attachment.png", "type": "image/png"}], "start": 1727096412363, "stop": 1727096412594}], "start": 1727096412363, "stop": 1727096412594, "uuid": "1eaca7e7-f194-4ef8-8f2c-4aa8886584dc", "historyId": "d3d39de6fc3cd407f5d66e2d343702f9", "fullName": "User Login to katalon-demo-cura application: Fail Test", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login to katalon-demo-cura application"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}